version: 2
updates:
  # Ruby gems using Bundler
  - package-ecosystem: bundler
    directory: /application
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    security-updates-only: true
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - ruby

  # JavaScript dependencies using npm
  - package-ecosystem: npm
    directory: /application
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    security-updates-only: true
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - javascript

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - github-actions
