
services:
  app:
    build: .
    container_name: oodd_dev
    restart: always
    volumes:
      - .:/app
      - ./data/metadata:/root/.downloads-for-ondemand
      - ./data/downloads:/root/downloads-ondemand
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true