version: '3.8'

services:
  app:
    build: .
    container_name: rails_dev
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true