name: Cypress E2E Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'application/**'
      - 'automated_tests/**'
      - '.github/workflows/cypress.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'application/**'
      - 'automated_tests/**'
      - '.github/workflows/cypress.yml'
  workflow_dispatch:

env:
  # OnDemand configuration
  OOD_VERSION: 3.1.7
  
  # Test configuration
  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Create credentials file
      run: |
        cd automated_tests
        echo '{"username":"${{ secrets.LOOP_USERNAME }}","password":"${{ secrets.LOOP_PASSWORD }}"}' > credentials.json
      env:
        LOOP_USERNAME: ${{ secrets.LOOP_USERNAME }}
        LOOP_PASSWORD: ${{ secrets.LOOP_PASSWORD }}
        
    - name: Create test directories
      run: |
        cd automated_tests
        mkdir -p cypress/screenshots cypress/videos cypress/results data/ood data/metadata data/downloads
        
    - name: Run Cypress tests
      run: |
        cd automated_tests
        make test-ci CYPRESS_BROWSER=${{ matrix.browser }}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-artifacts-${{ matrix.browser }}
        path: |
          automated_tests/cypress/screenshots/
          automated_tests/cypress/videos/
          automated_tests/cypress/results/
        retention-days: 30
        
    - name: Upload test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Cypress Test Results (${{ matrix.browser }})
        path: automated_tests/cypress/results/*.xml
        reporter: java-junit
        
    - name: Cleanup
      if: always()
      run: |
        cd automated_tests
        make clean
        rm -f credentials.json