site_name: OnDemand Loop Guide
site_url: https://iqss.github.io/ondemand-loop/
docs_dir: content

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
    - toc.integrate
  custom_dir: overrides
  palette:
    - scheme: default
      primary: '#212529'
      accent: '#a4c6fb'
    - scheme: slate
      primary: '#212529'
      accent: '#a4c6fb'

extra_css:
  - assets/bootstrap.css
  - assets/guide.css

nav:
  - Home: index.md
  - User Guide:
      - Introduction: user_guide/introduction.md
      - Getting Started: user_guide/getting_started.md
      - Creating Projects: user_guide/creating_projects.md
      - Exploring Remote Repositories: user_guide/exploring_remote_repositories.md
      - Downloading Files: user_guide/downloading_files.md
      - Uploading Files: user_guide/uploading_files.md
      - Using the File Browser: user_guide/using_the_file_browser.md
      - Viewing Download and Upload Status: user_guide/viewing_download_and_upload_status.md
  - Admin Guide: admin.md
  - Installation Guide: installation.md
  - Development Guide: development.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables

plugins:
  - search
