name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'application/**'
      - 'automated_tests/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'application/**'
      - 'automated_tests/**'

  workflow_dispatch:

env:
  # OnDemand configuration
  OOD_VERSION: 3.1.7

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build application
        run: make loop_build

      - name: Build Cypress
        working-directory: automated_tests
        run: make cypress_build

      - name: Start testing environment
        working-directory: automated_tests
        run: make env_up

      - name: Wait for OnDemand Loop
        run: .github/scripts/wait_for_loop.sh
        env:
          ENDPOINT: https://localhost:22200/pun/sys/loop
          OOD_USERNAME: ood
          OOD_PASSWORD: ood
          MAX_RETRIES: 20
          SLEEP_SECS: 10

      - name: Run Cypress tests
        working-directory: automated_tests
        run: make cypress_run

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress_artifacts
          path: |
            automated_tests/cypress/screenshots
            automated_tests/cypress/results
          if-no-files-found: ignore
