name: Build and Deploy from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the tag to release from (e.g., v1.2.3#2025-06-06)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Loop Tags
        uses: actions/checkout@v4
        working-directory: src
        with:
          fetch-depth: 0

      - name: Checkout specified tag
        working-directory: src
        run: |
          git fetch --tags
          git checkout "tags/${{ github.event.inputs.tag }}"

      - name: Build release
        working-directory: src
        run: make release_build

      - name: Run tests
        working-directory: src
        run: make test

      - name: Checkout Loop Production branch
        uses: actions/checkout@v4
        with:
          repository: IQSS/ondemand-loop
          ref: iqss_production
          path: target

      - name: Copy Loop new version
        run: |
          rm -rf target/*
          cp -R src/application/. target

      - name: Commit production release
        working-directory: target
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "OnDemand Loop deployment for version ${{ github.event.inputs.tag }}"
          git push
