name: Build and Deploy from Commit

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print deployment parameters
        run: |
          echo "🔧 Deploying release candidate:"
          echo "  - commit: ${{ inputs.commit_hash }}"
          echo "  - environment: Release QA"
          echo "  - branch: ondemand_loop_qa"

      - name: Checkout Loop at specific commit
        uses: actions/checkout@v4
        with:
          repository: IQSS/ondemand-loop
          path: src
          fetch-depth: 0
          ref: ${{ inputs.commit_hash }}

      - name: Git setup
        working-directory: src
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Build release
        working-directory: src
        run: make release_build

      - name: Checkout Loop Environment Branch
        uses: actions/checkout@v4
        with:
          repository: IQSS/ondemand-loop
          ref: ondemand_loop_qa
          path: target

      - name: Copy Loop new version
        run: |
          rsync -a --delete --exclude='.git' src/application/ target/

      - name: List contents of target
        run: ls -la target/

      - name: Commit production release
        working-directory: target
        run: |
          git add .
          git commit -m "OnDemand Loop deployment for commit ${{ inputs.commit_hash }}"
          git push
