name: Create Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Select the version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Loop SRC - ${{ github.sha }}
        uses: actions/checkout@v4
        with:
          path: src

      - name: Git setup
        working-directory: src
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Run tests using Docker via Make
        working-directory: src
        run: make test

      - name: Create release notes
        working-directory: src
        run: make release_notes

      - name: Bump version using Docker via Make
        working-directory: src
        run: make version VERSION_TYPE=${{ github.event.inputs.bump_type }}

      - name: Commit bumped version
        working-directory: src
        run: |
          git add application/VERSION
          git commit -m "Create release version"
          git push origin main

      - name: Read current version
        id: version
        working-directory: src/application
        run: |
          version=$(cat VERSION)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        working-directory: src
        run: |
          git tag -f "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}" --force
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        working-directory: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          body_path: application/release_notes.md



