name: Test OnDemand Loop

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test-ood-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v4
      - name: test loop app
        working-directory: .
        run: make test

